### ISSUE TITLE
RTL

### ISSUE THREAD

**Issue by tigrenok00** [valor-software/ng2-select#498]
Hi,
How can I display the items list right-to-left? Text-align: right did not work...
Thanks!

**Comment by park-brian** [comment]
``` CSS
.ui-select-container span {
  float: right;
}

```
